version: '26.1.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
